// Flat config. Layered deliberately: language presets, then the plugin
// recommended sets, then the narrow project rules, then Prettier last.
//
// House rule: no rule is turned off or downgraded without a comment saying why.
import js from "@eslint/js";
import vitest from "@vitest/eslint-plugin";
import eslintConfigPrettier from "eslint-config-prettier";
import { createTypeScriptImportResolver } from "eslint-import-resolver-typescript";
import importX from "eslint-plugin-import-x";
import promise from "eslint-plugin-promise";
import security from "eslint-plugin-security";
import sonarjs from "eslint-plugin-sonarjs";
import unicorn from "eslint-plugin-unicorn";
import vue from "eslint-plugin-vue";
import globals from "globals";
import tseslint from "typescript-eslint";
import vueParser from "vue-eslint-parser";

const TS_FILES = ["**/*.ts", "**/*.mts", "**/*.cts", "**/*.vue"];

export default tseslint.config(
  {
    // Generated, vendored, or owned by the build. `worker-configuration.d.ts`
    // is emitted by `wrangler types` and `data/` is generated by the brands
    // job; neither is hand-authored, so linting them is pure noise. `.local/`
    // is gitignored scratch space (see CLAUDE.md) -- never shipped, never
    // reviewed, and not written to the project's own style.
    ignores: [
      "dist/",
      ".wrangler/",
      "coverage/",
      "node_modules/",
      "worker-configuration.d.ts",
      "data/",
      ".local/",
      // Machine-written by scripts/build-jq-wasm.mjs from the pinned jq-wasm
      // package: Emscripten output, vendored verbatim and never hand-edited.
      "worker/mcp/jq/vendor/jq-glue.mjs",
      // Its hand-written types. A `.d.mts` is in no tsconfig `include` (the
      // compiler reaches it only through the import), so type-aware lint
      // cannot parse it.
      "worker/mcp/jq/vendor/jq-glue.d.mts",
      // Agent worktrees are full repo copies; linting them doubles the run and
      // reports their in-progress work as this checkout's failures.
      ".claude/",
    ],
  },

  js.configs.recommended,

  // Type-aware linting, scoped to files that actually belong to a tsconfig.
  ...tseslint.configs.strictTypeChecked.map((c) => ({ ...c, files: TS_FILES })),
  ...tseslint.configs.stylisticTypeChecked.map((c) => ({ ...c, files: TS_FILES })),
  {
    files: TS_FILES,
    languageOptions: {
      parserOptions: {
        projectService: {
          // eslint.config.js and any future loose .mjs helper are not in a
          // tsconfig `include`; the service needs permission to serve them
          // from its inferred default project rather than erroring.
          allowDefaultProject: ["*.js", "*.mjs"],
        },
        tsconfigRootDir: import.meta.dirname,
        extraFileExtensions: [".vue"],
      },
    },
  },
  {
    // The config file itself is plain JS, so the type-aware rules have no type
    // information to work from and would report on every line.
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
    extends: [tseslint.configs.disableTypeChecked],
  },

  unicorn.configs.recommended,
  importX.flatConfigs.recommended,
  {
    // import-x has to resolve modules the way TypeScript does -- the `@shared`
    // path alias, explicit `.ts` extensions, and `.vue` files -- or every
    // resolution-dependent rule (no-cycle, order, namespace) reports a false
    // positive on every import.
    settings: {
      "import-x/resolver-next": [
        createTypeScriptImportResolver({
          project: [
            "./tsconfig.worker.json",
            "./tsconfig.app.json",
            "./tsconfig.node.json",
            "./tsconfig.test.json",
          ],
          // Four projects is the intended shape here (Worker, SPA, Node, tests
          // each have incompatible globals); the root tsconfig.json already
          // references them. The warning does not apply.
          noWarnOnMultipleProjects: true,
        }),
      ],
    },
  },
  sonarjs.configs.recommended,
  security.configs.recommended,
  promise.configs["flat/recommended"],
  ...vue.configs["flat/recommended"],

  {
    files: ["**/*.vue"],
    languageOptions: {
      parser: vueParser,
      parserOptions: { parser: tseslint.parser },
    },
  },

  // Runtime globals per area.
  {
    files: ["src/**", "**/*.vue"],
    languageOptions: { globals: globals.browser },
  },
  {
    files: ["worker/**"],
    languageOptions: { globals: globals.serviceworker },
  },
  {
    files: ["scripts/**", "test/unit/**", "*.config.{js,mjs,ts}"],
    languageOptions: { globals: globals.node },
  },

  {
    // A leading underscore marks a deliberately unused binding. Interface
    // conformance (Hono middleware, EhrAdapter) regularly forces a
    // parameter that a particular implementation does not read.
    files: TS_FILES,
    plugins: { "@typescript-eslint": tseslint.plugin },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },

  {
    rules: {
      // FHIR payloads and Google Calendar responses use `null` as a real,
      // distinct value, and D1 columns are nullable. Rewriting those to
      // `undefined` would misrepresent the wire format.
      "unicorn/no-null": "off",
      // The domain vocabulary is abbreviations: FHIR, aud, iat, env, db, req,
      // res, params. Expanding them makes the code read worse, not better -- and
      // `Env`, `env` and `ctx` are the names Cloudflare's own Worker signatures
      // and generated types use, so renaming them would be actively wrong.
      "unicorn/prevent-abbreviations": "off",
      "unicorn/name-replacements": "off",
      // Single-line `/** ... */` is the universal TypeScript convention for a
      // one-line doc comment, and it is what editors surface on hover.
      "unicorn/single-line-block-comment-style": "off",
      // Module-scope registration is the API of both Hono (`app.get(...)`) and
      // a Vite config; there is no way to express either without it.
      "unicorn/no-top-level-side-effects": "off",
      // The auth layer is full of verb-phrase predicates -- verifyPassword,
      // verifyAccess, verifySession -- where the verb is the point. Forcing
      // them to `isPasswordValid` reads worse and hides that work is done.
      "unicorn/consistent-boolean-name": "off",
      // Vue single-file components are PascalCase by ecosystem convention,
      // which this rule's kebab-case default rejects.
      "unicorn/filename-case": [
        "error",
        { case: "kebabCase", ignore: [/^[A-Z][A-Za-z0-9]*\.vue$/u] },
      ],
      // Worker code ships to an environment with no Node built-ins on the hot
      // path; `node:` prefixed imports are used where needed, but this rule
      // also fires on browser APIs that have no Node equivalent here.
      "unicorn/prefer-top-level-await": "off",

      // Import hygiene.
      "import-x/order": [
        "error",
        {
          groups: ["builtin", "external", "internal", "parent", "sibling", "index", "type"],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],
      "import-x/no-cycle": ["error", { maxDepth: 6 }],
      // TypeScript itself resolves modules here (path aliases, `.ts`
      // extensions, `cloudflare:*` and `vite/client` virtual modules), and it
      // does so correctly; the plugin's resolver does not and reports false
      // positives on all four.
      "import-x/no-unresolved": "off",

      // `// TODO(waveN):` markers are a deliberate, reviewed part of this
      // repository: the build is staged in waves, and each marker names the
      // wave that fills it in. They are the plan, not forgotten work.
      "sonarjs/todo-tag": "off",
    },
  },

  // The worker/SPA boundary. Anything both sides need belongs in shared/, which
  // is the only module either may reach across into. The base rule rather than
  // the typescript-eslint one, deliberately: it also catches `import type`,
  // and a type crossing the boundary is exactly as much of a coupling as a
  // value crossing it.
  {
    files: ["worker/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/src/*", "src/*"],
              message:
                "Worker code must not import from the SPA (src/). Put anything both sides need in shared/.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["src/**", "**/*.vue"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/worker/*", "worker/*"],
              message:
                "SPA code must not import from the Worker (worker/). Put anything both sides need in shared/.",
            },
          ],
        },
      ],
    },
  },

  {
    files: ["test/**"],
    ...vitest.configs.recommended,
  },
  {
    files: ["test/**"],
    rules: {
      // Tests deliberately construct malformed payloads and poke at internals,
      // so the assertion-safety and complexity rules fight the point of them.
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "sonarjs/no-duplicate-string": "off",
      // Vitest's own `expect(value, message)` overload is how a loop-driven
      // assertion says which case failed; the rule's default cap of one
      // argument would forbid it.
      "vitest/valid-expect": ["error", { maxArgs: 2 }],
      // A table-driven `it.each` is sometimes clearer and sometimes not; this
      // rule cannot tell, and mechanically rewriting related-but-distinct
      // assertions into one parameterised case loses the failure names.
      "sonarjs/parameterized-tests": "off",
    },
  },
  {
    files: ["test/integration/**"],
    rules: {
      // `env` and `SELF` from `cloudflare:test` are marked deprecated in favour
      // of `cloudflare:workers`, but `wrangler types` does not yet emit the
      // `Cloudflare.Exports` interface that `exports.default.fetch()` needs, so
      // the deprecated imports are currently the only ones that type-check.
      // Revisit when the generated types catch up.
      "@typescript-eslint/no-deprecated": "off",
      "sonarjs/deprecation": "off",
    },
  },

  {
    files: ["scripts/**"],
    rules: {
      // The CLI helpers exist to print to the terminal.
      "no-console": "off",
      // They take file paths and secret names from argv by design; this rule
      // cannot tell a deliberate CLI argument from an injection sink.
      "security/detect-non-literal-fs-filename": "off",
      // These *are* CLI apps. A non-zero exit code is their error channel, and
      // throwing instead would print a stack trace over the prompt.
      "unicorn/no-process-exit": "off",
      // They shell out to `npx wrangler` deliberately: wrangler is a devDependency
      // of this repo, so resolving it through PATH is the intended behaviour.
      "sonarjs/no-os-command-from-path": "off",
    },
  },

  {
    // TEMPORARY. The open.epic brands slimmer landed in a separate change that
    // was written before this config existed, and it trips a set of style and
    // complexity rules that the rest of the repo passes. Rather than weaken
    // those rules everywhere, or blanket-ignore the files (which would drop the
    // security rules too), they are relaxed here and only here.
    //
    // TODO: refactor the slimmer -- chiefly splitting the 84-point
    // cognitive-complexity function -- and delete this whole block.
    files: ["scripts/slim-brands.mjs", "scripts/lib/**", "test/unit/slim-brands.test.ts"],
    rules: {
      "sonarjs/cognitive-complexity": "off",
      "sonarjs/super-linear-regex": "off",
      "sonarjs/no-unused-collection": "off",
      "sonarjs/no-redundant-jump": "off",
      "security/detect-object-injection": "off",
      "unicorn/no-array-sort": "off",
      "unicorn/no-break-in-nested-loop": "off",
      "unicorn/no-unreadable-for-of-expression": "off",
      "unicorn/prefer-await": "off",
      "unicorn/prefer-continue": "off",
      "unicorn/prefer-iterator-to-array": "off",
      "unicorn/prefer-logical-operator-over-ternary": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
    },
  },

  // Last: hand every formatting decision (quotes, indent, attribute wrapping)
  // to Prettier so the two never disagree.
  eslintConfigPrettier,
);
