/**
 * The Epic brand index: `data/epic-brands.json`, loaded once per isolate.
 *
 * The file is generated by `scripts/slim-brands.mjs` from Epic's public
 * "User-access Brands Bundle" and committed, so it is bundled with the Worker
 * rather than fetched at runtime -- an org's FHIR base has to be resolvable
 * while the admin is typing, and a 90 MB upstream bundle is not something to
 * reach for on a request path. Nothing in it is personal: it is the same public
 * directory any patient can read at open.epic.com.
 *
 * ### The canonical-name fix
 *
 * The slimmer dedupes brands by `fhirBaseUrl`, so several health systems that
 * share one Epic instance collapse into a single record: the first name wins and
 * the rest land in `aliases`. Searching only `name` therefore makes the other
 * systems unfindable -- the owner types the name on their insurance card and gets
 * nothing back.
 *
 * So every record is flattened to `names = [name, ...aliases]`, a search matches
 * *any* of them, and the DTO is rendered with the name that actually matched as
 * its `name` and the remaining ones as `aliases`. One record, addressed by
 * whichever of its names the owner knows.
 */

import brandsFile from "../data/epic-brands.json";

import type { BrandDto } from "@shared/types.ts";

/** One entry of `data/epic-brands.json`, as the slimmer writes it. */
interface RawBrand {
  id: string;
  name: string;
  aliases?: string[];
  portalUrl?: string;
  fhirBaseUrl: string;
  locations?: string[];
}

interface BrandsFile {
  generatedAt: string;
  source: string;
  count: number;
  brands: RawBrand[];
}

/**
 * A brand with its names flattened.
 *
 * `names[0]` is the slimmer's canonical name; the rest are the aliases of the
 * systems that share the same FHIR endpoint. The list is never empty.
 */
export interface BrandRecord {
  id: string;
  names: string[];
  fhirBaseUrl: string;
  portalUrl: string | null;
  locations: string[];
}

/** How many matches `searchBrands` returns. The admin UI shows a short list. */
export const BRAND_SEARCH_LIMIT = 20;

// Annotated rather than inferred: `resolveJsonModule` gives the import a type
// built from the literal contents of the committed file, so the annotation is what
// pins the shape the generator promises -- and what fails the build if a future
// slimmer drops a field this module reads.
const file: BrandsFile = brandsFile;

function toRecord(raw: RawBrand): BrandRecord {
  return {
    id: raw.id,
    names: [raw.name, ...(raw.aliases ?? [])],
    fhirBaseUrl: raw.fhirBaseUrl,
    portalUrl: raw.portalUrl ?? null,
    locations: raw.locations ?? [],
  };
}

const records: readonly BrandRecord[] = file.brands.map((raw) => toRecord(raw));

/** Every brand, flattened. Read-only: the array is shared by every request. */
export function allBrands(): readonly BrandRecord[] {
  return records;
}

/** When the committed index was generated. Reported by the overview. */
export function brandsGeneratedAt(): string {
  return file.generatedAt;
}

/**
 * Render a record as the API DTO, with `matched` as the display name.
 *
 * `matched` is whichever of the record's names the search hit, so a system that
 * shares an endpoint is shown under its own name and the endpoint's other names
 * become its aliases.
 */
export function toBrandDto(record: BrandRecord, matched?: string): BrandDto {
  const name = matched !== undefined && record.names.includes(matched) ? matched : record.names[0];
  return {
    id: record.id,
    // `names` is built from a required field, so index 0 always exists; the
    // fallback only satisfies noUncheckedIndexedAccess.
    name: name ?? "",
    aliases: record.names.filter((candidate) => candidate !== name),
    fhirBaseUrl: record.fhirBaseUrl,
    portalUrl: record.portalUrl,
    locations: record.locations,
  };
}

/** Ranks, lowest first. A name match always beats an alias or a location. */
const RANK = {
  namePrefix: 0,
  nameSubstring: 1,
  aliasPrefix: 2,
  aliasSubstring: 3,
  location: 4,
} as const;

interface Match {
  record: BrandRecord;
  /** The name that matched, which becomes the DTO's `name`. */
  matched: string;
  rank: number;
}

/** Best (lowest) rank for one record against `query`, or null for no match. */
function rankOf(record: BrandRecord, query: string): { matched: string; rank: number } | null {
  let best: { matched: string; rank: number } | null = null;
  for (const [index, candidate] of record.names.entries()) {
    const lower = candidate.toLowerCase();
    const isAlias = index > 0;
    let rank: number | null = null;
    if (lower.startsWith(query)) rank = isAlias ? RANK.aliasPrefix : RANK.namePrefix;
    else if (lower.includes(query)) rank = isAlias ? RANK.aliasSubstring : RANK.nameSubstring;
    if (rank !== null && (best === null || rank < best.rank)) best = { matched: candidate, rank };
  }
  if (best !== null) return best;
  // A location match is the last resort: "St. Louis, MO" finds the systems there
  // when the owner does not know what the organisation calls itself.
  const byLocation = record.locations.some((location) => location.toLowerCase().includes(query));
  return byLocation ? { matched: record.names[0] ?? "", rank: RANK.location } : null;
}

/**
 * Case-insensitive search over names, aliases and locations.
 *
 * An empty query returns nothing rather than the whole index: the endpoint is a
 * type-ahead, and 770 records is not a useful answer to "".
 */
export function searchBrands(query: string, limit = BRAND_SEARCH_LIMIT): BrandDto[] {
  const needle = query.trim().toLowerCase();
  if (needle === "") return [];

  const matches: Match[] = [];
  for (const record of records) {
    const hit = rankOf(record, needle);
    if (hit !== null) matches.push({ record, matched: hit.matched, rank: hit.rank });
  }

  // Sorted in place: `matches` is local to this call, so nothing shared is mutated.
  matches.sort(
    (a, b) => a.rank - b.rank || a.matched.localeCompare(b.matched, "en", { sensitivity: "base" }),
  );
  return matches.slice(0, limit).map((match) => toBrandDto(match.record, match.matched));
}

/** One brand by the id `/api/brands` handed out. Null when it is unknown. */
export function brandById(id: string): BrandDto | null {
  const record = records.find((candidate) => candidate.id === id);
  return record === undefined ? null : toBrandDto(record);
}
